version: "3"

services:
  registry:
    build: verdaccio
    ports:
      - 4873:4873
  s3:
    image: minio/minio
    command: server /data
    volumes:
      - minio/data:/data
    ports:
      - 9000:9000
